services:
  gambler:
    build: 
      context: ./gambler
      dockerfile: ./Dockerfile
    container_name: gambler
    volumes:
      - ./gambler:/app/shared
      - ./data:/app/data
    env_file:
      - .env

